create table news (
                      id bigint generated by default as identity,
                      content varchar(5000),
                      image_url varchar(255),
                      is_published boolean not null,
                      published_at timestamp(6),
                      title varchar(255) not null,
                      author_id bigint,
                      video_id bigint,
                      primary key (id)
);

create table users (
                       id bigint generated by default as identity,
                       avatar_url varchar(255),
                       created_at timestamp(6),
                       email varchar(255) not null,
                       full_name varchar(255) not null,
                       is_active boolean not null,
                       password varchar(255) not null,
                       role varchar(255) check ((role in ('USER','ADMIN','INSTRUCTOR'))),
                       username varchar(255) not null,
                       primary key (id)
);

create table videos (
                        id bigint generated by default as identity,
                        content_type varchar(255),
                        description varchar(1000),
                        duration varchar(255),
                        file_name varchar(255) not null,
                        file_path varchar(255),
                        file_size bigint,
                        likes integer,
                        thumbnail_url varchar(255),
                        title varchar(255) not null,
                        uploaded_at timestamp(6),
                        views integer,
                        uploaded_by bigint,
                        primary key (id)
);