-- =====================================================
-- Актуальная схема makeup (новостной/видео backend).
--
-- Единственный источник схемы — Flyway. Приложение подключается с
-- ddl-auto=none, поэтому Hibernate ничего не создаёт и не меняет.
-- В БД храним только ключи объектов MinIO (не URL и не префиксы бакетов),
-- время — в UTC (timestamp).
-- =====================================================

-- Для поиска по title (LIKE '%...%') — trigram-индекс в V2.
create extension if not exists pg_trgm;

-- =====================================================
-- users
-- =====================================================
create table users (
    id            bigint generated by default as identity primary key,
    username      varchar(50)  not null,
    email         varchar(255) not null,
    password_hash varchar(255) not null,
    full_name     varchar(255) not null,
    avatar_url    varchar(500),
    role          varchar(20)  not null default 'USER'
        check (role in ('USER', 'ADMIN', 'INSTRUCTOR')),
    is_active     boolean      not null default true,
    created_at    timestamp  not null default now(),
    updated_at    timestamp  not null default now(),
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email)
);

-- =====================================================
-- videos
-- object_key / thumbnail_key — ключи объектов в бакетах videos/thumbnails.
-- duration_seconds — целое (было varchar). views/likes_count — bigint со счётчиком.
-- =====================================================
create table videos (
    id               bigint generated by default as identity primary key,
    title            varchar(255) not null,
    description      varchar(1000),
    object_key       varchar(255) not null,
    thumbnail_key    varchar(255),
    content_type     varchar(100),
    file_size        bigint,
    duration_seconds integer,
    status           varchar(20)  not null default 'PUBLISHED'
        check (status in ('UPLOADING', 'PROCESSING', 'PUBLISHED', 'FAILED', 'ARCHIVED')),
    views            bigint       not null default 0,
    likes_count      bigint       not null default 0,
    uploaded_by      bigint       not null,
    created_at       timestamp  not null default now(),
    updated_at       timestamp  not null default now(),
    constraint fk_videos_uploaded_by foreign key (uploaded_by)
        references users (id) on delete restrict
);

-- =====================================================
-- video_likes — факт лайка (кто и что), likes_count у видео — денормализация.
-- =====================================================
create table video_likes (
    user_id    bigint      not null,
    video_id   bigint      not null,
    created_at timestamp not null default now(),
    primary key (user_id, video_id),
    constraint fk_video_likes_user foreign key (user_id)
        references users (id) on delete cascade,
    constraint fk_video_likes_video foreign key (video_id)
        references videos (id) on delete cascade
);

-- =====================================================
-- news
-- status вместо boolean is_published; deleted_at — soft delete.
-- =====================================================
create table news (
    id           bigint generated by default as identity primary key,
    title        varchar(255) not null,
    content      varchar(5000),
    image_key    varchar(255),
    video_id     bigint,
    author_id    bigint       not null,
    status       varchar(20)  not null default 'DRAFT'
        check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    published_at timestamp,
    created_at   timestamp  not null default now(),
    updated_at   timestamp  not null default now(),
    deleted_at   timestamp,
    constraint fk_news_video foreign key (video_id)
        references videos (id) on delete set null,
    constraint fk_news_author foreign key (author_id)
        references users (id) on delete restrict
);

-- =====================================================
-- media_jobs — outbox/очередь фоновой обработки медиа (превью).
-- Воркер забирает PENDING-задачи (SKIP LOCKED), ставит RUNNING,
-- по завершении DONE/FAILED с ретраями.
-- =====================================================
create table media_jobs (
    id         bigint generated by default as identity primary key,
    video_id   bigint       not null,
    type       varchar(20)  not null default 'THUMBNAIL',
    status     varchar(20)  not null default 'PENDING'
        check (status in ('PENDING', 'RUNNING', 'DONE', 'FAILED')),
    attempts   integer      not null default 0,
    last_error varchar(1000),
    created_at timestamp  not null default now(),
    updated_at timestamp  not null default now(),
    constraint fk_media_jobs_video foreign key (video_id)
        references videos (id) on delete cascade
);
