create table if not exists users (
    id bigint generated by default as identity,
    avatar_url varchar(255),
    created_at timestamp(6),
    email varchar(255) not null,
    full_name varchar(255) not null,
    is_active boolean not null,
    password varchar(255) not null,
    role varchar(255) check (role in ('USER', 'ADMIN', 'INSTRUCTOR')),
    username varchar(255) not null,
    primary key (id),
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email)
);

create table if not exists videos (
    id bigint generated by default as identity,
    content_type varchar(255),
    description varchar(1000),
    duration varchar(255),
    file_name varchar(255) not null,
    file_path varchar(255),
    file_size bigint,
    likes integer,
    thumbnail_path varchar(255),
    title varchar(255) not null,
    uploaded_at timestamp(6),
    views integer,
    uploaded_by bigint,
    primary key (id),
    constraint fk_videos_uploaded_by foreign key (uploaded_by) references users (id)
);

create table if not exists news (
    id bigint generated by default as identity,
    content varchar(5000),
    image_url varchar(255),
    is_published boolean not null,
    published_at timestamp(6),
    title varchar(255) not null,
    author_id bigint,
    video_id bigint,
    primary key (id),
    constraint fk_news_author foreign key (author_id) references users (id),
    constraint fk_news_video foreign key (video_id) references videos (id)
);

create index if not exists idx_news_published_at on news (is_published, published_at desc);
create index if not exists idx_videos_uploaded_at on videos (uploaded_at desc);